[package]
name = "aarch64_qemuvirt"
version = "0.0.1"
edition = "2021"

[dependencies]
gagelen = { path = "../kernel", features = ["aarch64_pgt48oa"] }
tests = { path = "../tests", artifact = "bin" }
align-data = "0.1"
cortex-a = "8.1"
