[package]
name = "aarch64_qemuvirt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel = { path = "../kernel", features = ["aarch64_pgt48oa"] }
log = "0.4"

[features]
launch_tests = []
