[package]
name = "goose"
version = "0.1.0"
authors = ["cohenarthur <arthur.cohen@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qemu-exit = { git = "https://github.com/andre-richter/qemu-exit.git" }
cfg-if = "0.1.10"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.10"
rlibc = "1.0.0"

# [profile.dev]
# panic = "abort"
#
# [profile.release]
# panic = "abort"

[package.metadata.bootimage]
run-args = ["-serial", "stdio"]
test-args = ["-nographic", "-monitor", "none", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 253
