[package]
name = "goose"
version = "0.1.0"
authors = ["cohenarthur <arthur.cohen@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qemu-exit = "1.0.0"
cfg-if = "0.1.10"
bitfield = "0.13.2"

# [profile.dev]
# panic = "abort"
#
# [profile.release]
# panic = "abort"
