[package]
name = "goose"
version = "0.1.0"
authors = ["cohenarthur <arthur.cohen@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1.10"

[target.'cfg(target_arch = "x86_64")'.dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
test-args = ["-nographic", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 253
