[package]
name = "hal_riscv64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal_core = { path = "../hal_core" }
modular-bitfield = "0.11"
sbi = "0.2.0"
riscv = "0.8.0"
