[package]
name = "hal_aarch64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal_core = { path = "../hal_core" }
tock-registers = "0.8"
cortex-a = "8.1"
log = "0.4"
