[package]
name = "riscv64_qemuvirt"
version = "0.0.1"
edition = "2021"

[dependencies]
gagelen = { path = "../kernel", features = ["riscv64_sv39"] }
tests = { path = "../tests", artifact = "bin" }
align-data = "0.1.0"
