name: Clippy

on:
  pull_request:
  push:
    branches:
      main

jobs:
  clippy_riscv64:
    runs-on: ubuntu-latest
    env:
      TARGET: riscv64gc-unknown-none-elf
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            components: clippy
            targets: ${{ env.TARGET }}
      - run: cd riscv64_qemuvirt && cargo clippy --all-features --target ${{ env.TARGET }}

  clippy_aarch64:
    runs-on: ubuntu-latest
    env:
      TARGET: aarch64-unknown-none
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            components: clippy
            targets: ${{ env.TARGET }}
      - run: cd aarch64_qemuvirt && cargo clippy --all-features --target ${{ env.TARGET }}
