name: Doc

on:
  pull_request:
  push:
    branches:
      master

jobs:
  doc_riscv64:
    runs-on: ubuntu-latest
    env:
      TARGET: riscv64gc-unknown-none-elf
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            targets: ${{ env.TARGET }}

      - name: Build doc
        run: cd kernel && cargo doc --target ${{ env.TARGET }} --all-features

  doc_aarch64:
    runs-on: ubuntu-latest
    env:
      TARGET: aarch64-unknown-none
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            targets: ${{ env.TARGET }}

      - name: Build doc
        run: cd kernel && cargo doc --target ${{ env.TARGET }} --all-features