name: Format

on:
  pull_request:
  push:
    branches:
      master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Format
        run: cargo fmt -- --check
