name: Format

on:
  pull_request:
  push:
    branches:
      main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v27

      - name: Format
        run: nix develop --command sh -c "
          cargo fmt -- --check
          "
