name: Kernel Unit Tests CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [riscv64gc-unknown-none-elf]

    steps:
      - uses: actions/checkout@v2

      - name: Rustup setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install qemu
        run: |
          sudo apt update
          sudo apt install qemu-system

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.target }}

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }} --verbose
