name: Kernel Unit Tests CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install qemu
        run: sudo apt install qemu-kvm

      - name: Cargo install bootimage
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: bootimage

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
