name: Kernel Unit Tests CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [riscv64gc-unknown-none-elf]

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          echo TARGET=${{ matrix.target }} >> $GITHUB_ENV

      - name: Rustup setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install qemu
        run: |
          sudo apt update
          sudo apt install qemu-system

      - name: Make check
        run: make check

      - name: Make build
        run: make build

      - name: Make test
        run: make test
