name: Tests

on: pull_request

jobs:
  tests_riscv64:
    runs-on: ubuntu-22.04
    env:
      TARGET: riscv64gc-unknown-none-elf
      BIN: riscv64_qemuvirt
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: ${{ env.TARGET }}
            override: true

      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install qemu-system-misc opensbi

      - name: Build fixtures
        run: make -C kernel/fixtures $TARGET

      - name: cargo test
        run: cargo test --release --target ${{ env.TARGET }} --bin ${{ env.BIN }}
