name: Test

on:
  pull_request:
  push:
    branches:
      main

jobs:
  test_riscv64:
    runs-on: ubuntu-latest
    env:
      TARGET: riscv64gc-unknown-none-elf
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            components: clippy
            targets: ${{ env.TARGET }}

      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install qemu-system-misc opensbi

      - run: cd riscv64_qemuvirt && cargo run -F launch_tests

  test_aarch64:
    runs-on: ubuntu-latest
    env:
      TARGET: aarch64-unknown-none
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            components: clippy
            targets: ${{ env.TARGET }}

      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install qemu-system-arm

      - run: cd aarch64_qemuvirt && cargo run -F launch_tests
