name: Test

on:
  pull_request:
  push:
    branches:
      main

jobs:
  test_riscv64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v27

      - name: Run tests
        run: nix develop --command sh -c "
          cd riscv64_qemuvirt &&
          cargo run -F launch_tests
          "

  test_aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v27

      - name: Enter nix
        run: nix develop

      - name: Run tests
        run: nix develop --command sh -c "
          cd aarch64_qemuvirt &&
          cargo run -F launch_tests
          "
